<template>
  <div>
    <v-toolbar flat app>
      <div class="d-flex align-center">
        <v-avatar>
          <v-img
            src="../assets/logo.jpg"
            class="mr-2"
            contain
            @click.native="$router.push('/')"
          />
        </v-avatar>
      </div>
      <v-btn
        class="mr-2" 
        flat
        color="white" 
        elevation="0" 
        @click.native="$router.push('categories')">
        Categories
      </v-btn>
      <v-btn 
        color="white" 
        flat
        elevation="0" 
        @click.native="$router.push('about')">
        About
      </v-btn>
    </v-toolbar>
    <v-divider></v-divider>
  </div>
</template>